### ISSUE TITLE
`ContentScannerRestError` raised when downloading files somehow does not make it to the servlet

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-content-scanner-python#35]
When doing some manual testing while I had a bogus value for the proxy configuration setting (meaning the content scanner would not be able to reach homeservers), I realised that, while the connection error was correctly turned into a `ContentScannerRestError but did not seem to get properly propagated up to the servlet code (which turns it into a JSON response):

```
$ python -m matrix_content_scanner.mcs -c config.yaml
2022-11-03 18:01:32,168 - matrix_content_scanner.httpserver - 69 - INFO - None - Starting listener on 0.0.0.0:8080
2022-11-03 18:01:32,168 - twisted - 147 - INFO - None - Site starting on 8080
2022-11-03 18:01:32,168 - twisted - 147 - INFO - None - Starting factory <twisted.web.server.Site object at 0x7f599c9273a0>
2022-11-03 18:01:33,108 - matrix_content_scanner.scanner.file_downloader - 368 - INFO - GET-0 - Sending GET request to https://matrix.org/_matrix/media/v3/download/[...]
2022-11-03 18:01:33,110 - twisted - 147 - INFO - None - Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f599c9316c0>, <HostnameEndpoint 10.0.0.1:3128>)
^C2022-11-03 18:01:57,492 - twisted - 147 - INFO - None - Received SIGINT, shutting down.
2022-11-03 18:01:57,494 - matrix_content_scanner.scanner.file_downloader - 375 - ERROR - GET-0 - An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].
2022-11-03 18:01:57,495 - twisted - 147 - INFO - None - Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f599c9316c0>, <HostnameEndpoint 10.0.0.1:3128>)
2022-11-03 18:01:57,496 - twisted - 147 - INFO - None - (TCP Port 8080 Closed)
2022-11-03 18:01:57,496 - twisted - 147 - INFO - None - Stopping factory <twisted.web.server.Site object at 0x7f599c9273a0>
2022-11-03 18:01:57,497 - twisted - 147 - INFO - None - Main loop terminated.
Unhandled error in Deferred:
2022-11-03 18:01:57,514 - twisted - 147 - CRITICAL - None - Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 700, in errback
    self._startRunCallbacks(fail)
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
    self._runCallbacks()
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 1750, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/__init__.py", line 82, in _async_render
    self._send_error(
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/__init__.py", line 121, in _send_error
    request.finish()
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/web/server.py", line 277, in finish
    return http.Request.finish(self)
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/web/http.py", line 1161, in finish
    raise RuntimeError(
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

2022-11-03 18:01:57,515 - twisted - 147 - CRITICAL - None - 
Traceback (most recent call last):
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/scanner/file_downloader.py", line 369, in _get
    resp: IResponse = await self._agent.request(
twisted.internet.error.ConnectError: An error occurred while connecting: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/__init__.py", line 78, in _async_render
    code, response = await method_handler(request)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/scan.py", line 44, in on_GET
    await self._scanner.scan_file(media_path)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/scanner/scanner.py", line 174, in scan_file
    media = await self._file_downloader.download_file(
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/scanner/file_downloader.py", line 111, in download_file
    file = await self._get_file_content(url)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/scanner/file_downloader.py", line 230, in _get_file_content
    code, body, headers = await self._get(url)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/scanner/file_downloader.py", line 376, in _get
    raise ContentScannerRestError(
matrix_content_scanner.utils.errors.ContentScannerRestError: Failed to reach the remote server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/__init__.py", line 82, in _async_render
    self._send_error(
  File "/home/babolivier/Documents/matrix/mcs-python-final/matrix_content_scanner/servlets/__init__.py", line 121, in _send_error
    request.finish()
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/web/server.py", line 277, in finish
    return http.Request.finish(self)
  File "/home/babolivier/.virtualenvs/mcs-py310/lib/python3.10/site-packages/twisted/web/http.py", line 1161, in finish
    raise RuntimeError(
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

(at the 9th line, I've `Ctrl+C`'d the program since my request was hanging forever)

**Comment by babolivier** [comment]
Turns out I misidentified the source of the issue: the request was hanging due to a timeout.
